# Generated by Django 2.2.1 on 2019-05-19 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=100)),
                ('birthdate', models.IntegerField()),
                ('mail', models.EmailField(max_length=100)),
                ('name', models.CharField(max_length=50)),
                ('sex', models.CharField(max_length=6)),
                ('username', models.CharField(max_length=50)),
                ('days_since_signup', models.IntegerField()),
                ('acquisition_channel', models.CharField(max_length=50)),
                ('job_title', models.CharField(max_length=50)),
                ('company_size', models.IntegerField()),
                ('completed_form', models.IntegerField()),
                ('visited_pricing', models.IntegerField()),
                ('registered_for_webinar', models.IntegerField()),
                ('attended_webinar', models.IntegerField()),
                ('industry', models.CharField(max_length=50)),
                ('converted', models.IntegerField()),
                ('is_manager', models.IntegerField()),
                ('acquisition_channel_Cold_Call', models.IntegerField()),
                ('acquisition_channel_Cold_Email', models.IntegerField()),
                ('acquisition_channel_Organic_Search', models.IntegerField()),
                ('acquisition_channel_Paid_Leads', models.IntegerField()),
                ('acquisition_channel_Paid_Search', models.IntegerField()),
                ('company_size_1_10', models.IntegerField()),
                ('company_size_1000_10000', models.IntegerField()),
                ('company_size_10001_plus', models.IntegerField()),
                ('company_size_101_250', models.IntegerField()),
                ('company_size_11_50', models.IntegerField()),
                ('company_size_251_1000', models.IntegerField()),
                ('company_size_51_100', models.IntegerField()),
                ('industry_Financial_Services', models.IntegerField()),
                ('industry_Furniture', models.IntegerField()),
                ('industry_Heavy_Manufacturing', models.IntegerField()),
                ('Scandanavion_Design', models.IntegerField()),
                ('Transportation', models.IntegerField()),
                ('Internet', models.IntegerField()),
                ('score', models.IntegerField()),
            ],
        ),
    ]
