# Generated by Django 2.2.1 on 2019-05-19 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='birthdate',
            field=models.DateField(),
        ),
    ]
