# Generated by Django 2.2.1 on 2019-05-20 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_auto_20190519_1945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='company_size',
            field=models.CharField(max_length=20),
        ),
    ]
