# Generated by Django 2.2.1 on 2019-05-20 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0004_auto_20190519_2052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='is_manager',
            field=models.BooleanField(),
        ),
    ]
