from django.db import models

class Lead(models.Model):
    # lead_ref_id=models.CharField(max_length=100, blank=True, unique=True, default=uuid.uuid4) -- not sure if this is necessary
    address=models.CharField(max_length=100)
    birthdate=models.CharField(max_length=15)
    mail=models.EmailField(max_length=100)
    name=models.CharField(max_length=50)
    sex=models.CharField(max_length=6)
    username=models.CharField(max_length=50)
    days_since_signup=models.IntegerField()
    acquisition_channel=models.CharField(max_length=50)
    job_title=models.CharField(max_length=50)
    company_size=models.CharField(max_length=20)
    completed_form=models.IntegerField()
    visited_pricing=models.IntegerField()
    registered_for_webinar=models.IntegerField()
    attended_webinar=models.IntegerField()
    industry=models.CharField(max_length=50)
    converted=models.IntegerField()
    is_manager=models.BooleanField()
    acquisition_channel_Cold_Call=models.IntegerField()
    acquisition_channel_Cold_Email=models.IntegerField()
    acquisition_channel_Organic_Search=models.IntegerField()
    acquisition_channel_Paid_Leads=models.IntegerField()
    acquisition_channel_Paid_Search=models.IntegerField()
    company_size_1_10=models.IntegerField()
    company_size_1000_10000=models.IntegerField()
    company_size_10001_plus=models.IntegerField()
    company_size_101_250=models.IntegerField()
    company_size_11_50=models.IntegerField()
    company_size_251_1000=models.IntegerField()
    company_size_51_100=models.IntegerField()
    industry_Financial_Services=models.IntegerField()
    industry_Furniture=models.IntegerField()
    industry_Heavy_Manufacturing=models.IntegerField()
    Scandanavion_Design=models.IntegerField()
    Transportation=models.IntegerField()
    Internet=models.IntegerField()
    score=models.FloatField()
